name: appgestion
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  video_player: ^2.10.0
  charts_flutter: ^0.12.0
  fl_chart: ^0.66.0
  http: ^1.4.0
  lucide_icons: ^0.257.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_pdfview: ^1.0.4
  flutter_secure_storage: ^9.0.0  
  share_plus: ^7.2.1
  intl: ^0.17.0  # Pour DateFormat
  material_design_icons_flutter: ^7.0.7296  # Pour plus d'ic√¥nes
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pdf: ^3.10.7
  printing: ^5.12.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqflite_common: ^2.3.0
  drift: ^2.14.1
  drift_flutter: ^0.1.0
  sqlite3_flutter_libs: ^0.5.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.14.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
